heat_template_version: 2015-10-15

description: This is a Heat template

parameters:
  key_name:
    type: string
    description : Name of a key pair to enable SSH access to instances.
    default: jasond

  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    constraints:
      - custom_constraint: nova.flavor
    default: 4 GB Performance 

  image:
    type: string
    description: >
      Name or ID of the image to use for the WordPress server.
    default: f4bbbce2-50b0-4b07-bf09-96c175a45f4b


resources:
  asg_test:
    type: Rackspace::AutoScale::Group
    properties:
      groupConfiguration:
        name: { get_param: "OS::stack_name" }
        metadata:
          rax-heat: { get_param: "OS::stack_id" }
        maxEntities: 3
        minEntities: 1
        cooldown: 120
      launchConfiguration:
        type: launch_stack
        args:
          stack:
            template_url: https://raw.githubusercontent.com/jasondunsmore/useful-heat-templates/master/autoscale-stack-launch-type-template-only.yaml
            disable_rollback: False
            environment:
              resource_registry:
                Heat::InstallConfigAgent: https://raw.githubusercontent.com/rackerlabs/heat-ci/master/dev/bootconfig.yaml
            parameters:
              flavor: {get_param: flavor}
              image: {get_param: image}
            timeout_mins: 30

