heat_template_version: 2015-10-15

description: This is a Heat template

parameters:
  key_name:
    type: string
    description : Name of a key pair to enable SSH access to instances.
    default: default

  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    constraints:
      - custom_constraint: nova.flavor
    default: 4 GB Performance 

  image:
    type: string
    description: >
      Name or ID of the image to use for the WordPress server.
    default: CentOS 7 (PVHVM)

  db_name:
    type: string
    description: WordPress database name
    default: wordpress
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters

  db_username:
    type: string
    description: The WordPress database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters

resources:
  asg_test:
    type: Rackspace::AutoScale::Group
    properties:
      groupConfiguration:
        name: { get_param: "OS::stack_name" }
        metadata:
          rax-heat: { get_param: "OS::stack_id" }
        maxEntities: 3
        minEntities: 1
        cooldown: 120
      launchConfiguration:
        type: launch_stack
        args:
          stack:
            template:
              heat_template_version: 2015-10-15
              description: This is a Heat template
              
              parameters:
                key_name:
                  type: string
                  description : Name of a key pair to enable SSH access to instances.
                  default: jasond
              
                flavor:
                  type: string
                  description: Flavor to use for the WordPress server.
                  constraints:
                    - custom_constraint: nova.flavor
                  default: 4 GB Performance 
              
                image:
                  type: string
                  description: >
                    Name or ID of the image to use for the LAMP server.
                    The image must have the software config agents baked-in.
                  default: f4bbbce2-50b0-4b07-bf09-96c175a45f4b
              
              
              resources:
                lamp_config:
                  type: OS::Heat::SoftwareConfig
                  properties:
                    group: script
                    config: |
                      #!/bin/bash -v
                      apt-get install -y apache2 mysql-server php5 php-pear php5-mysql
                      cat > /var/www/html/info.php << EOF
                      <?php
                      phpinfo();
                      ?>
                      EOF
              
                lamp_deploy:
                  type: OS::Heat::SoftwareDeployment
                  properties:
                    signal_transport: TEMP_URL_SIGNAL
                    config:
                      get_resource: lamp_config
                    server:
                      get_resource: lamp_server
              
                lamp_server:
                  type: OS::Nova::Server
                  properties:
                    image: {get_param: image}
                    flavor: 2 GB Performance
                    key_name: {get_param: key_name}
                    software_config_transport: POLL_TEMP_URL
                    user_data_format: SOFTWARE_CONFIG
              
              outputs:
                server_php_info:
                  description: URL for PHP info on LAMP server
                  value:
                    str_replace:
                      template: http://host/info.php
                      params:
                        host: {get_attr: [lamp_server, accessIPv4]}

            disable_rollback: False
            environment:
              resource_registry:
                Heat::InstallConfigAgent: https://raw.githubusercontent.com/rackerlabs/heat-ci/master/dev/bootconfig.yaml
            parameters:
              flavor: {get_param: flavor}
              image: {get_param: image}
            timeout_mins: 30

