heat_template_version: 2014-10-16 

description: |
  Test template for AWS supported resources 

parameters:

resources:
  ElasticLoadBalancer:
        type: AWS::ElasticLoadBalancing::LoadBalancer
        properties:
            AvailabilityZones: []
            Instances:
              - "58b1c8b4-1b85-4eb4-9566-4e6445326076"
            Listeners: [{
                LoadBalancerPort: 8945,
                InstancePort: 80,
                Protocol: "HTTP"
            }]
            HealthCheck:
                Target: "HTTP:80/"
                HealthyThreshold: 3
                UnhealthyThreshold: 10
                Interval: 10
                Timeout: 60
