heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running Apache.

resources:

  wp_web_server:
    type: "OS::Nova::Server"
    properties:
      flavor: 1GB Standard Instance
      image: 5b0d5891-f80c-412a-9b73-cc996de9d719
      key_name: foo

  wp_web_server_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: wp_web_server
    properties:
      username: root
      private_key:
        get_file: /tmp/foo
      host: { get_attr: [ wp_web_server, accessIPv4 ] }
      kitchen: https://github.com/rackspace-orchestration-templates/wordpress-multi
      chef_version: 11.16.2
      node:
        apache:
          listen_ports: [8080]
          timeout: 30
          serversignature: "Off"
          traceenable: "Off"
