heat_template_version: 2013-05-23

resources:
  test1:
    type: "OS::Heat::TestResource"
    properties:
      value: Test
      update_replace: False

  test2:
    type: "OS::Heat::TestResource"
    depends_on: test1
    properties:
      value: Test
      update_replace: False
