heat_template_version: 2013-05-23

resources:
  test1:
    type: "OS::Heat::TestResource"
    properties:
      value: Test
      update_replace: False

  test2:
    type: "OS::Heat::TestResource"
    properties:
      value: {get_attr: [test1, value]}
      update_replace: False

outputs:
  test2_value:
    value: {get_attr: [test2, value]}
