#
# This is a hello world HOT template just defining a single compute
# server.
#
heat_template_version: 2013-05-23

description: >
  Hello world HOT template that just defines a single server.
  Contains just base features to verify base HOT support.

parameters:
  foo:
    type: string
    description: Name of an existing key pair to use for the server
    hidden: true
    default: secret

resources:
  random_key_name:
    type: OS::Heat::RandomString
    properties:
      foo:
        str_replace:
          template: |
            foo bar
          params:
            foo: [1, 2]

outputs:
  foo:
    description: Show foo parameter value
    value: {get_param: foo}
