heat_template_version: 2013-05-23

description: |
  A template implementation of a resource that provides a hello world application server

resources:

  the_resource:
    type: OS::Heat::RandomString

  child_template:
    type: https://raw.githubusercontent.com/jasondunsmore/useful-heat-templates/master/show.yaml
    properties:
      show: { get_attr: [ the_resource, show ] }
