heat_template_version: 2013-05-23

resources:
  lb:
    type: Rackspace::Cloud::LoadBalancer
    properties:
      nodes:
        - addresses: [162.242.216.226]
          port: 80
      protocol: TCP
      port: 80
      virtualIps:
        - {"type": "PUBLIC", "ipVersion": "IPV4"}
