heat_template_version: '2015-10-15'

parameter_groups:
-   label: WordPress Settings
    parameters: [wordpress_url, wordpress_sitename, wordpress_user, wordpress_email]

parameters:
    flavor:
        constraints:
        -   allowed_values: [1 GB General Purpose v1, 2 GB General Purpose v1, 4 GB
                    General Purpose v1, 8 GB General Purpose v1]
        default: 4 GB General Purpose v1
        description: Flavor of Cloud Server to use for WordPress
        label: Server Flavor
        type: string
    server_count:
        constraints:
        -   range: {max: 10, min: 0}
        default: 0
        description: Number of secondary web nodes
        label: Number of Secondary Servers
        type: number
    wordpress_email: {default: admin@example.com, description: E-mail Address for
            WordPress Admin User, label: WordPress Admin E-mail, type: string}
    wordpress_sitename: {default: Example Site, description: Title to use for WordPress
            Site, label: Site Title, type: string}
    wordpress_url:
        constraints:
        - {allowed_pattern: '^[a-zA-Z0-9.-]{1,255}.[a-zA-Z]{2,15}$', description: Must
                be a valid domain name}
        default: example.com
        description: Domain to use with WordPress Site
        label: Site Domain
        type: string
    wordpress_user:
        constraints:
        - {allowed_pattern: '^[a-zA-Z0-9]*$', description: Only can contain A-Z and
                0-9}
        default: admin
        description: Username for WordPress login
        label: WordPress Admin Username
        type: string

resources:
    holland_pass: {type: 'OS::Heat::RandomString'}
    load_balancer:
        depends_on: [deploy_wordpress, wordpress_secondary]
        properties:
            algorithm: ROUND_ROBIN
            contentCaching: ENABLED
            metadata:
                rax-heat: {get_param: 'OS::stack_id'}
            name:
                str_replace:
                    params:
                        stack: {get_param: 'OS::stack_name'}
                    template: stack_Load_Balancer
            nodes:
            -   addresses:
                -   get_attr: [wordpress_server, networks, private, 0]
                condition: ENABLED
                port: 80
            -   addresses:
                    get_attr: [wordpress_secondary, private_ip]
                condition: ENABLED
                port: 80
            port: 80
            protocol: HTTP
            sessionPersistence: HTTP_COOKIE
            virtualIps:
            - {ipVersion: IPV4, type: PUBLIC}
        type: Rackspace::Cloud::LoadBalancer
    other_config:
        properties:
            config: "---\n- name: Install and configure Lsyncd\n  hosts: localhost\n\
                \  connection: local\n  roles:\n  - lsync\n  - firewall\n"
            group: ansible
            inputs:
            - {default: '[]', name: lsync_servers, type: CommaDelimitedList}
        type: OS::Heat::SoftwareConfig
    ssh_key:
        properties:
            name: {get_param: 'OS::stack_id'}
            save_private_key: true
        type: OS::Nova::KeyPair
    upload_role_config:
        properties:
            config: '#!/bin/bash

                set -e

                git clone -b ''stable'' --single-branch --progress https://github.com/rackspace-orchestration-templates/ansible-roles.git
                /etc/ansible/roles > $heat_outputs_path.results 2>&1

                '
            group: script
            outputs:
            - {name: results}
        type: OS::Heat::SoftwareConfig
    wordpress_backup:
        depends_on: wordpress_server
        properties:
            BackupConfigurationName:
                str_replace:
                    params:
                        stack: {get_param: 'OS::stack_name'}
                    template: stack Weekly Backup
            DayOfWeekId: 0
            Frequency: Weekly
            HourInterval: null
            Inclusions:
            - {FileItemType: Folder, FilePath: /var/spool/holland}
            - {FileItemType: Folder, FilePath: /var/www}
            NotifyFailure: true
            NotifyRecipients: {get_param: wordpress_email}
            StartTimeAmPm: AM
            StartTimeHour: 1
            StartTimeMinute: 0
            TimeZoneId: Central Standard Time
            VersionRetention: 30
            host_ip_address:
                get_attr: [wordpress_server, accessIPv4]
        type: Rackspace::Cloud::BackupConfig
    wordpress_config:
        properties:
            config: "---\n- name: Install and configure WordPress\n  hosts: localhost\n\
                \  connection: local\n  roles:\n  - common\n  - nginx\n  - php-fpm\n\
                \  - holland\n  - wordpress\n  - phpmyadmin\n"
            group: ansible
            inputs:
            - {default: '[]', name: firewall_nodes, type: CommaDelimitedList}
            - {default: '[]', name: firewall_node_rules, type: CommaDelimitedList}
        type: OS::Heat::SoftwareConfig
    wordpress_pass: {type: 'OS::Heat::RandomString'}
    wordpress_secondary:
        properties:
            count: {get_param: server_count}
            resource_def:
                properties:
                    apache_default_domain: {get_param: wordpress_url}
                    master_server:
                        get_attr: [wordpress_server, networks, private, 0]
                    parent_stack_id: {get_param: 'OS::stack_id'}
                    server_flavor: {get_param: flavor}
                    server_image: f4bbbce2-50b0-4b07-bf09-96c175a45f4b
                    server_name:
                        str_replace:
                            params:
                                stack: {get_param: 'OS::stack_name'}
                            template: stack-secondary-%index%
                    ssh_key: {get_resource: ssh_key}
                type: https://raw.githubusercontent.com/rackspace-orchestration-templates/wordpress-small/master/wordpress-small-secondary.yaml
        type: OS::Heat::ResourceGroup
    wordpress_server:
        properties:
            config_drive: true
            flavor: {get_param: flavor}
            image: f4bbbce2-50b0-4b07-bf09-96c175a45f4b
            key_name: {get_resource: ssh_key}
            metadata:
                build_config: backup_agent_only,monitoring_defaults
                rax-heat: {get_param: 'OS::stack_id'}
            name: {get_param: 'OS::stack_name'}
            software_config_transport: POLL_TEMP_URL
            user_data_format: SOFTWARE_CONFIG
        type: OS::Nova::Server

outputs:
    secondary_ips:
        description: Secondary Node IPs
        value:
            get_attr: [wordpress_secondary, public_ip]
    server_ip:
        description: Server Public IP
        value:
            get_attr: [wordpress_server, accessIPv4]
    ssh_private_key:
        description: SSH Private Key
        value:
            get_attr: [ssh_key, private_key]
    wordpress_admin_url:
        description: WordPress Admin URL
        value:
            str_replace:
                params:
                    domain: {get_param: wordpress_url}
                template: https://domain/wp-admin/
    wordpress_login_password:
        description: WordPress Admin Password
        value:
            get_attr: [wordpress_pass, value]
    wordpress_login_user:
        description: WordPress Admin User
        value: {get_param: wordpress_user}
    wordpress_public_ip:
        description: Load Balancer IP
        value:
            get_attr: [load_balancer, PublicIp]
    wordpress_public_url:
        description: WordPress Public URL
        value:
            str_replace:
                params:
                    domain: {get_param: wordpress_url}
                template: http://domain/
