heat_template_version: 2013-05-23

resources:
  random-string-cluster:
    type: OS::Heat::ResourceGroup
    properties:
      count: 4
      resource_def:
        type: OS::Heat::RandomString
  single-random-string:
      type: OS::Heat::RandomString
      properties:
        length: 8

outputs:
  foo:
    description: Show foo value
    value: {get_attr: [random-string-cluster, value]}
