heat_template_version: 2013-05-23

resources:
  test_random_string:
    type: OS::Heat::RandomString

outputs:
  foo:
    value: { get_attr: [test_random_string, value] }
    description: Random string value
