heat_template_version: 2015-10-15
resources:
  gitlab_server:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: "OS::stack_name" }
      flavor: 4 GB Performance
      image: CentOS 7 (PVHVM)
  gitlab_server_http_check:
    type: Rackspace::CloudMonitoring::Check
    properties:
      entity: { get_resource: gitlab_server }
      type: remote.http
      label:
        str_replace:
          template: stack HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [gitlab_server, accessIPv4] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [gitlab_server, accessIPv4] }
      target_receiver: IPv4
