heat_template_version: 2013-05-23

parameters:
  image:
    type: string

resources:
  hello_world:
    type: "Rackspace::Cloud::Server"
    properties:
      flavor: 4 GB General Purpose v1
      image: { get_param: image }
