heat_template_version: 2014-10-16 

description: |
  Test template for ResourceGroup resource capabilities 

parameters:
  host_count:
    type: number
    default: 2

resources:

  service_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: host_count}
      resource_def:
        type: OS::Nova::Server
        properties:
          image: 6f29d6a6-9972-4ae0-aa80-040fa2d6a9cf # Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
          flavor: 4 GB Performance 
