heat_template_version: 2013-05-23
resources:
    rg:
        type: OS::Heat::ResourceGroup
        properties:
            count: 125
            resource_def:
                type: https://raw.githubusercontent.com/jasondunsmore/useful-heat-templates/master/rand_str.yaml

