heat_template_version: 2013-05-23

parameters:
  subscriber:
    type: string
    default: mailto:me@test.com

resources:
  test_queue:
    type: OS::Zaqar::Queue
    properties:
      name: foo

  test_subscription:
    type: OS::Zaqar::Subscription
    properties:
      name: foo
      subscriber: { get_param: subscriber }
      ttl: 3600

